version: '3.8'

services:
  app:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./app:/code/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - testNet
  db:
    image: "postgres:latest"
    restart: always
    expose:
      - 5432
    env_file:
      - .envdb
    networks:
      - testNet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
networks:
  testNet: